### ISSUE TITLE
Specs delegation

### ISSUE THREAD

**Issue by Orland0x** [snapshot-labs/sx-starknet#13]

**Comment by pscott** [comment]
ideas, discussed internally. Posting here to keep it noted somewhere, but would need some more detailing.

Pass an additional arg,  block_hash, to the new_proposal method of the VC.
On a new_proposal, the Voting Contract would also query the Delegate-Registry, asking for a "snapshot" of the current delegations for this particular space (basically a copy of delegation[space]). (we must make sure that block_hash corresponds to one of the latest blocks on Ethereum at time of creation of the proposal)

The VC would store this copy, and when a new vote is cast, it checks the delegation snapshot (kept internally). The voting power is then queried to the Balance Reader (by providing the block_hash stored for the proposal).
