### ISSUE TITLE
Felt packing inside Proposal Struct

### ISSUE THREAD

**Issue by Orland0x** [snapshot-labs/sx-starknet#184]
Currently there are 4 timestamps stored inside the proposal struct. 32 bits is sufficient for each timestamp and a felt is 251. Therefore we can pack them all inside a single felt to reduce the storage requirements and therefore gas costs. 

Low Priority as this adds complexity and will not reduce cost per vote.

**Comment by pscott** [comment]
Could be useful: https://github.com/gaetbout/starknet-felt-packing :D
