### ISSUE TITLE
Use session keys to broadcast vote and propose

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-starknet#254]
### Motivation
Reduce gas costs to vote in Ethereum DAOs by performing the expensive Ethereum signature verification only once per session. All other votes made by the user during the session are authenticated by a Stark signature with a key stored in the browser. 

### Implementation 
Will be implemented as an authenticator contract called `EthSigSessionKey.cairo`. Spaces will be able to whitelist this authenticator for members of the space to use. The session duration is variable and can be set at deployment inside the constructor. 

### Interface 
```
@constructor 
func constructor(session_length : felt)
end

# Returns session key if it exists and hasn't expired
func get_session_key(eth_address: felt)  -> (key: felt):
end

# Performs EC recover on the Ethereum signature and stores the session key in a 
# mapping indexed by the recovered Ethereum address
@external 
func generate_session_key_from_sig(
    r : Uint256,
    s : Uint256,
    v : felt,
    salt : Uint256,
    session_public_key: felt
):
end

# Checks signature is valid and if so, removes session key for user
@external 
func revoke_session_key(sig_len: felt, sig: felt*):
end

# Calls get_session_key with the ethereum address (calldata[0]) to check that a session is active.
# If so, perfoms stark signature verification to check the sig is valid. If so calls execute with the payload. 
@external
func authenticate(sig_len: felt, sig: felt*, target: felt, function_selector: felt, calldata_len: felt, calldata: felt*)
end
```

**Comment by Orland0x** [comment]
Also adding `EthTxSessionKey.cairo` which works in the same way except it authenticates a user via an Eth Tx rather than a Eth Sig
