### ISSUE TITLE
Better failure messages

### ISSUE THREAD

**Issue by Orland0x** [snapshot-labs/sx-starknet#255]
Eg if a proposal has not been initialised and someone tries to cast a vote, it should fail with that error message. Currently it does not. 

There is most likely a few cases of this in the space contract.

**Comment by pscott** [comment]
The current error message is "invalid proposal id" I believe. I think this is the only occurrence of "voting on a invalid proposal". Would you like to change the error message?

https://github.com/snapshot-labs/sx-core/blob/dbc2ebda0fb395c73482bd659c189b7aacf93772/contracts/starknet/Space.cairo#L867-L871
