### ISSUE TITLE
Use `le_felt` for comparison

### ISSUE THREAD

**Issue by pscott** [snapshot-labs/sx-starknet#343]

**Comment by Orland0x** [comment]
This goes for asserts too. We need to use the `_felt` suffix versions of the assert functions to ensure they work with values in the full range up to 251 bits and not just up to 2**128 (range check bound)

**Comment by Orland0x** [comment]
thought more about this and had a change of opinion. We do two types of number comparisons: ones on uint256s (voting power, quorum etc), and ones on timestamps.  Timestamps will always be smaller than the range check bound and therefore its more efficient to use the comparison functions only defined over this range.
