### ISSUE TITLE
Create a voting strategy for checkpoint ERC20 and NFTs

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-starknet#374]

**Comment by pscott** [comment]
Currently working on implementing a Starknet version of: https://github.com/Amxx/EIPs/blob/vote_with_delegation/EIPS/eip-5805.md

**Comment by bonustrack** [comment]
Here is the contract for EIP-5805 https://github.com/snapshot-labs/starknet-delegation
