### ISSUE TITLE
refactor: use error codes for revert messages

### ISSUE THREAD

**Issue by Orland0x** [snapshot-labs/sx-starknet#422]
revert messages must be 31 characters. Use codes so better messages can be given.

**Comment by pscott** [comment]
I believe 31 chars ought to be enough to convey the error. And they will be natively supported by StarkScan, whereas codes mihgt not be?

**Comment by pscott** [comment]
I believe 31 chars ought to be enough to convey the error. And they will be natively supported by StarkScan, whereas codes mihgt not be?
