### ISSUE TITLE
refactor: how to represent `bytes` in Cairo1?

### ISSUE THREAD

**Issue by pscott** [snapshot-labs/sx-starknet#429]
Currently we're using `Array<felt252>` but I'm not sure this is the best way of representing `bytes`, the reason being that if we want to pack for example 50 bytes, we'll be using 248 on each `felt252`, but we will probably *not* use the remaining `4` bits on each `felt252`...

For a more visual explanation:

| array[0] | array[1] | array[2] |
|---|---|---|
| 00101010 01101010 ... 10100011 **_0110_**  | 11010001 10010100 ... 01111110 **_1101_**  | ... ... |

As you can see, if we go with a "dumb" approach of packing bits 8 by 8, then we'll be left out with a "waste" of 4 bits per felt252.
An ideal library would instead pack them 8 by 8 and keep a "carry" when it moves to the following `felt252` (i.e, would use the last 4 bits of array[0] and first 4 bits of array[1]).

I think it might be worth it to write a separate crate that does that (and potentially, strings could be handled this way too).

**Comment by Orland0x** [comment]
there is no requirement for us to use use an array of bytes like we do in solidity. `bytes` is used for serialized data resulting from `abi.encode`, the equivalent serialization in cairo 1 is provided by the `Serde` trait which results in an `Array<felt252>`.
