### ISSUE TITLE
audit: L-03 Functional Implementation Contract

### ISSUE THREAD

**Issue by Orland0x** [snapshot-labs/sx-starknet#560]
The L1AvatarExecutionStrategy is intended to be accessed with a proxy pattern. The implementation should be disabled as much as possible to limit the attack surface, but it is initialized with user-supplied parameters. To further reduce its functionality, consider ensuring there is no valid owner, target or space.

**Comment by Orland0x** [comment]
We discussed this for sx-evm and decided against this approach as it prevents the strategy from being used stand alone (without proxy). Situation is no different here so I see no reason for us to address this. 

Our factory used to deploy these proxies will be the same as sx-evm which executes the initializer at deployment, therefore preventing the  possibility of any kind of malicious master implementation initialization.  https://github.com/snapshot-labs/sx-evm/blob/df37a70673067300a3a6c0541740117a86d0bc59/src/ProxyFactory.sol#L12C2-L12C2

**Comment by pscott** [comment]
I opened back the CS audit report and saw in finding 6.5 that they noted : 

> Code corrected:
> The constructor now disables the contract by transferring ownership to address(1), which means no delegate call can be performed from the implementation contract.

However I'm not sure I see that in the code? I have a hard time recalling exactly how we addressed this

**Comment by Orland0x** [comment]
> I opened back the CS audit report and saw in finding 6.5 that they noted :
> 
> > Code corrected:
> > The constructor now disables the contract by transferring ownership to address(1), which means no delegate call can be performed from the implementation contract.
> 
> However I'm not sure I see that in the code? I have a hard time recalling exactly how we addressed this

think this issue was referring to the timelock execution strategy, not the avatar one. as you can see no dummy initialization was used on the avatar: https://github.com/snapshot-labs/sx-evm/blob/df37a70673067300a3a6c0541740117a86d0bc59/src/execution-strategies/AvatarExecutionStrategy.sol#L31C8-L31C8
