### ISSUE TITLE
audit: N-05 Voting Strategy Limitations

### ISSUE THREAD

**Issue by Orland0x** [snapshot-labs/sx-starknet#567]
The Space contract could be more robust in its management of voting strategies. In
particular, there could be a mechanism to re-enable removed strategies. This would allow the
add_voting_strategies function to prevent duplicates.

**Comment by Orland0x** [comment]
Interesting idea. Could be added quite simply but not sure how much usage it would get

**Comment by pscott** [comment]
Not sure we want that.. easy to mess up, and hard to track in the UI I believe ?

**Comment by bonustrack** [comment]
It's unlikely we would add this system in the UI, it's adding more complexity, and to be consistent with SX-EVM I wouldn't do that change.
