### ISSUE TITLE
audit: N-09 Unindexed Events

### ISSUE THREAD

**Issue by Orland0x** [snapshot-labs/sx-starknet#571]
The StarknetSpaceManager events are not indexed.
Consider indexing the space parameter to facilitate off-chain processing.

**Comment by Orland0x** [comment]
Not sure we need to index the events , things have been working fine without so far.

**Comment by pscott** [comment]
Indexing keys simply makes the life of an indexer easier because it can use this key to search for specific events.

more info: https://ethereum.stackexchange.com/questions/8658/what-does-the-indexed-keyword-do
