### ISSUE TITLE
Emit an event when a space is created

### ISSUE THREAD

**Issue by pscott** [snapshot-labs/sx-starknet#91]

**Comment by pscott** [comment]
@bonustrack @Orland0x I don't remember why I created this issue: is it a request from you guys or just something I thought about and forgot to properly document ? 🙈

**Comment by bonustrack** [comment]
This is a request from me, if we issue an event with space settings when the space is deployed we can catch this info with Checkpoint to populate these settings on the API. Currently it's hardcoded.

**Comment by pscott** [comment]
@bonustrack got it :) easy to add! :)

**Comment by Orland0x** [comment]
cool, the event will be emitted in the space factory once that exists though right?

**Comment by bonustrack** [comment]
Yep
