### ISSUE TITLE
Add Amarna to CI

### ISSUE THREAD

**Issue by pscott** [snapshot-labs/sx-starknet#97]
Amana is a static analyzer developped by trail of bits (https://blog.trailofbits.com/2022/04/20/amarna-static-analysis-for-cairo-programs/). I think it would make sense for us to add it to the CI :D

**Comment by Orland0x** [comment]
waiting for new version with cairo 0.1.0 support

**Comment by zzuziak** [comment]
Hey hello @pscott what's the status with this issue?

**Comment by pscott** [comment]
@zzuziak  Amarna still doesn't allow us to deactivate some lints when we need them so can't really use it unforuntately
