### ISSUE TITLE
Use of EthAddress in interfaces

### ISSUE THREAD

**Issue by pscott** [snapshot-labs/sx-starknet#99]
Currently, some interfaces / functions are using `EthAddress` because the MVP was made with L1 transactions in mind.
However in the future, we  might want to change to `Uint256` (and not felt, because some keys on other chains might not fit in a `felt`!).

(This issue refers to the `get_voting_power` interface for example, or the `vote` and `propose` function of the space contract :))

**Comment by Orland0x** [comment]
Using a general `Address` type
